### ISSUE TITLE
Manually code sample of data

### ISSUE THREAD

**Issue by nniiicc** [OpenDataLiteracy/Feedback#4]
I will send this by email and we will review the classification April 21, 2017.

**Comment by nniiicc** [comment]
Sample issue for coding here: https://docs.google.com/spreadsheets/d/1lugxssdgS_LaspCsA8JAMqiPuI13QwoN30a7BxAac3g/edit#gid=1598819504

**Comment by annieyan** [comment]
Some observations/thoughts from the literature:
- the possibility of one comment belongs to multiple issues
- the issues have a hierarchical structure maybe
- user generated tags might be dirty and random. Predefined categories might be better
-  if possible, we could manually label all of them

**Comment by annieyan** [comment]
Maybe categorize the issues to broad categories such as "data availablility""data quality""metadata quality". Then we use finer grained sub-categories in our classification. For example, broken link might belongs to data availability...look forward to your thoughts on this
